### PR TITLE
Fix #263 force snapshot bad increment

### LINKED ISSUE #263: CurrentVersion issue: nextVersionTag and forceSnapshot yield nextVersionTag+1
### Issue
When `-Prelease.forceSnapshot` is specified and last tag is `nextVersionTag`, than `currentVersion` is incorrect -> the version is incremented once more.

Given:
 tag 'release-1.2.0-alpha'
 -Prelease.forceSnapshot

When:
 gradle currentVersion
 
Then:
 BUG: currentVersion == '1.2.1-SNAPSHOT'
 IMHO SHOULD be: currentVersion == '1.2.0-SNAPSHOT'

### Current status of the issue
I have reproduced this issue in your tests (`VersionResolverTest.groovy`) and I will now make commit to my forked version of the axion-release-plugin.

I will you let you know when I find some solution.

Please let me know whether this is really a BUG and whether you see any possible things with the code I should be aware of.

### PR DESCRIPTION
**Pull request by trohr**
Hello,

I have been able to fix issue #263.

Now, when `-Prelease.forceSnapshot` is specified and tag on previous commits is a `nextVersionTag`, than resolved version is snapshot version of the nextVersionTag. The version is not incremented once more as before the fix.

```groovy
// This test case reproduces issue #263
def "should return previous version from last release tag and current from next version when on next version tag (and force snapshot)"() {

    given: "there is nextVersionTag on current commit (2.0.0-alpha)"
    repository.tag('release-1.1.0')
    repository.commit(['*'], 'some commit')
    repository.tag('release-2.0.0-alpha')
    def versionRulesForceSnapshot = versionProperties().forceSnapshot().build()

    when: "resolving version with property 'release.forceSnapshot'"
    VersionContext version = resolver.resolveVersion(versionRulesForceSnapshot, tagRules, nextVersionRules)

    then: "the resolved version should be snapshot towards the next version (2.0.0-SNAPSHOT)"
    version.previousVersion.toString() == '1.1.0'

    // The following assertion was failing -- if forceSnapshots specified, than 'nextReleaseVersion'
    // was incremented once again yielding the 2.0.1-SNAPSHOT version, which is NOT CORRECT.
    version.version.toString() == '2.0.0'
    version.snapshot
}
```

I have also added more tests 
Please review the changes.

Thank you,
Tomas Rohrbacher

### CODE REVIEW

File: src/test/groovy/pl/allegro/tech/build/axion/release/domain/VersionResolverTest.groovy [hunk 1]
```diff
@@ -135,6 +160,28 @@ class VersionResolverTest extends RepositoryBasedTest {
...
+        repository.tag('release-2.0.0-alpha')
+        def versionRulesForceSnapshot = versionProperties().forceSnapshot().build()
+
+        when: "resolving version with property 'release.forceSnapshot'"
+        VersionContext version = resolver.resolveVersion(versionRulesForceSnapshot, tagRules, nextVersionRules)
+
+        then: "the resolved version should be snapshot towards the next version (2.0.0-SNAPSHOT)"
+        version.previousVersion.toString() == '1.1.0'
+
+        // The following assertion fails -- if forceSnapshots specified, than 'nextReleaseVersion'
```
Comment (adamdubiel) [inline src/test/groovy/pl/allegro/tech/build/axion/release/domain/VersionResolverTest.groovy]: is this comment still needed?
