### PR TITLE
Snapshot dependencies check added

### LINKED ISSUE #41: release plugin needs to validate that build is not using snapshot dependencies
If a build has included snapshot libraries, the release plugin should fail as it is not reproducible build script.

### PR DESCRIPTION
**Pull request by vbuell**
Closes #41. 
This adds snapshot dependencies check functionality.

### CODE REVIEW

**Comment by vbuell** [comment]
And yeah. I remember that you were planning to use Pre-build hooks, but they doesn't help much here since HookContext doesn't have an access to project instance (which is for good reason).

File: src/main/groovy/pl/allegro/tech/build/axion/release/domain/SnapshotDependenciesChecker.groovy [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+        allDependenciesVersions.removeAll(projectVersions)
+        return allDependenciesVersions
+    }
+
+    boolean isSnapshot(Dependency dependency) {
+        dependency.version?.endsWith("-SNAPSHOT")
+    }
+
+    String toFullVersion(it) {
+        "${it.group}:${it.name}:${it.version}"
```
Comment (szpak) [inline src/main/groovy/pl/allegro/tech/build/axion/release/domain/SnapshotDependenciesChecker.groovy]: I know that in case of Gradle in many places you cannot be sure what object is inside, but here `Project` should be quite safe. IMHO this code would be more readable with less `def`s.

**Comment by adamdubiel** [comment]
I will give it some more look in the evening, but looks good to me, thanks! You are right, hooks are no good for things like this.

File: src/main/groovy/pl/allegro/tech/build/axion/release/domain/SnapshotDependenciesChecker.groovy (hunk 1 above)
Comment (adamdubiel) [inline src/main/groovy/pl/allegro/tech/build/axion/release/domain/SnapshotDependenciesChecker.groovy]: hm, i see only 2 collection defs here, which look quite necessary, maybe give some groovy-magic sample?

Comment (szpak) [inline src/main/groovy/pl/allegro/tech/build/axion/release/domain/SnapshotDependenciesChecker.groovy]: I think that @vbuell rebased the code in the meantime (hmm, usually I was able to get "outdated diff", but in that case it seems to be not possible outside a small diff on the conversation page), from something like:
```
def projectVersions = ...
def allDependenciesVersions = ...
```
I also didn't like `String toFullVersion(it) {}` and it thought that `Project` could be used there, but it seems that there could be also a `Dependency` instance which has nothing common with `Project` (regarding a class hierarchy).

Comment (adamdubiel) [inline src/main/groovy/pl/allegro/tech/build/axion/release/domain/SnapshotDependenciesChecker.groovy]: Okay, i see :)

**Comment by adamdubiel** [comment]
Thanks for another contribution @vbuell :)
